apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: istio-ingress-pool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.49.240-192.168.49.250
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: advertise
  namespace: metallb-system
spec:
  ipAddressPools:
    - istio-ingress-pool
