apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app1
  namespace: argocd
  annotations:
    #argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: git@github.com:shackdan/minikube.git
    path: manifests/manifests/app1
    targetRevision: HEAD
    helm:
      values: |
        customerService:
          hostname: demo.thenewtonlab.com
  destination:
    server: https://kubernetes.default.svc
    namespace: app1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
