apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-cni
  namespace: argocd
  annotations:
  #argocd.argoproj.io/sync-wave: "0"
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  project: default
  source:
    chart: cni
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: 1.26.2
    helm:
      values: |
        global:
          platform: minikube
        components:
          cni:
            enabled: true
            namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true