---
apiVersion: v1
kind: Namespace
metadata:
  name: otel-demo
---
# Jaeger All-in-One
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jaeger
  template:
    metadata:
      labels:
        app: jaeger
    spec:
      containers:
      - name: jaeger
        image: jaegertracing/all-in-one:latest
        ports:
        - containerPort: 16686
        - containerPort: 14268
        env:
        - name: COLLECTOR_OTLP_ENABLED
          value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  namespace: otel-demo
spec:
  selector:
    app: jaeger
  ports:
  - name: ui
    port: 16686
    targetPort: 16686
  - name: collector
    port: 14268
    targetPort: 14268
  - name: otlp-grpc
    port: 4317
    targetPort: 4317
  - name: otlp-http
    port: 4318
    targetPort: 4318
---
# Simple Demo App with OpenTelemetry
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
  namespace: otel-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: otel/demo:latest
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://jaeger:4318"
        - name: OTEL_SERVICE_NAME
          value: "demo-service"
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app
  namespace: otel-demo
spec:
  selector:
    app: demo-app
  ports:
  - port: 8080
    targetPort: 8080
  type: LoadBalancer