#virtualservice.yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ printf "%s-%s" .Release.Namespace "service" }}
spec:
  hosts:
    - {{ .Values.customerService.hostname }}
  gateways:
    - {{ printf "%s-%s" .Release.Namespace "demo-gateway" }}
  http:
    - route:
        - destination:
            host: app3-service.app3.svc.cluster.local
            port:
              number: 80

---
# gateway.yaml
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ printf "%s-%s" .Release.Namespace "demo-gateway" }}
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - {{ .Values.customerService.hostname }}

